---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, xvfb, zlib1g-dev, fontconfig-config, libx11-dev, libfreetype6, libxext6, libxrender1, openssl, build-essential, xorg, libssl-dev]
    timezone: UTC
    locale: ru_RU.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.77.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/application/web
    servername: myApp.vb
mysql:
    install: '1'
    root_password: '123'
    database: vitoopdb
    user: user
    password: password
    dump: false #devops/ansible/files/live_vitoop.dump.sql
php:
    install: '1'
    ppa: php
    packages: [php7.0-cli, php7.0-intl, php7.0-mcrypt, php7.0-curl, php7.0-common, php7.0-gd, php7.0-fpm, php7.0-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

