image: php:7.1.28
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y unzip git
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - cd application
          - composer install --prefer-dist --no-scripts --ignore-platform-reqs --optimize-autoloader
          - vendor/bin/phpunit --colors=never