version: "3.4"

volumes:
  app-vitoop:
    driver: local
    driver_opts:
      type: none
      device: $PWD/application
      o: bind

networks:
  backend:

services:
  vitoopdb:
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./devops/docker/states/db/vitoop
        target: /var/lib/mysql
    networks:
      - backend
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitoop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"

  web:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - app-vitoop:/srv:nocopy
      - ./devops/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./devops/docker/php
    depends_on:
      - vitoopdb
    networks:
      - backend
    volumes:
      - app-vitoop:/srv:nocopy
      - ./downloads:/srv/downloads