version: "3.4"

volumes:
  app-vitoop:
    external: true

networks:
  backend:

services:
  vitoopdb:
    image: mariadb:10.3.18
    volumes:
      - type: bind
        source: ./devops/docker/states/db/vitoop
        target: /var/lib/mysql
      - ./backups:/srv/backups
    networks:
      - backend
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitoop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"

  web:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - app-vitoop:/srv:nocopy
      - ./devops/docker/nginx/site.dev.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./devops/docker/php
    environment:
      XDEBUG_CONFIG: 'client_host=${DOCKER_HOST_IP} client_port=9003 remote_enable=1 idekey=PHPSTORM max_nesting_level=512 '
    depends_on:
      - vitoopdb
    networks:
      - backend
    volumes:
      - app-vitoop:/srv:nocopy
      - ./downloads:/srv/downloads

#  smtp:
#    image: namshi/smtp
#    networks:
#      - backend
#    restart: always
#    ports:
#      - "25:25"