version: "3.4"

networks:
  backend:

services:
  vitoopdb:
    image: mariadb:10.11
    volumes:
      - ./devops/docker/states/db/vitoop:/var/lib/mysql
      - ./backups:/srv/backups
      - ./devops/docker/maria/conf:/etc/mysql/conf.d
    networks:
      - backend
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitoop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"

  web:
    image: nginx:alpine-slim
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - ./application:/srv
      - ./devops/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./devops/docker/php
    depends_on:
      - vitoopdb
    networks:
      - backend 
    volumes:
      - ./application:/srv
      - ./downloads:/srv/downloads

#  smtp:
#    image: namshi/smtp
#    networks:
#      - backend
#    restart: always
#    ports:
#      - "25:25"