# Vitoop/InfomgmtBundle/src/Resources/config/validation.yml
Vitoop\InfomgmtBundle\Entity\Resource:
    properties:
        name:
            - NotBlank:
                message: "Bitte gebe einen Namen für die Resource ein."
            - Length:
                max: 128
                maxMessage: "Der Name der Resource darf nicht mehr als {{ limit }} Zeichen haben."

Vitoop\InfomgmtBundle\Entity\Book:
    properties:
        author:
            - NotBlank:
                message: "Bitte gebe einen Autor ein. Wenn der Autor unbekannt ist, gebe \"??\" ein."
            - Length:
                max: 256
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        publisher:
            - NotBlank:
                message: "Bitte gebe einen Verlag ein. Wenn der Verlag unbekannt ist, gebe \"??\" ein."
            - Length:
                max: 256
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        issuer:
            - Length:
                max: 256
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        isbn13:
            - NotBlank:
                message: "Bitte gebe einen ISBN-13 ein. Wenn der ISBN-13 unbekannt ist, gebe \"??\" ein."
            - Length:
                min: 13
                max: 17
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        isbn10:
            - NotBlank:
                message: "Bitte gebe einen ISBN-10 ein. Wenn der ISBN-10 unbekannt ist, gebe \"??\" ein."
            - Length:
                min: 10
                max: 13
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        year:
            - NotBlank:
                message: "Bitte gebe einen Jahr ein. Wenn der Jahr unbekannt ist, gebe \"??\" ein."
        tnop:
            - NotBlank:
                message: "Bitte gebe die Seitenanzahl ein. Falls unbekannt bitte 0 angeben.."
            - Range:
                min: 0
                minMessage: "Negative Seitenzahlen sind sinnlos."
                max: 100000
                maxMessage: "Mehr als 100.000 Seiten sind unwahrscheinlich."

Vitoop\InfomgmtBundle\Entity\Pdf:
    properties:
        author:
            - NotBlank:
                message: "Bitte gebe einen Autor ein. Wenn der Autor unbekannt ist, gebe \"??\" ein."
            - Length:
                max: 128
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        publisher:
            - Length:
                max: 128
                maxMessage: "Dieses Feld darf nicht mehr als {{ limit }} Zeichen haben."
        url:
            - NotBlank:
                message: "Bitte gebe eine Url für das pdf ein."
            - Length:
                max: 255
                maxMessage: "Die Url darf nicht mehr als {{ limit }} Zeichen haben."
            - Url:
                message: "Die Url ist ungültig. Bitte gebe auch http://, https:// oder ftp:// mit an."
                protocols: [http,https,ftp]
        tnop:
            - NotBlank:
                message: "Bitte gebe die Seitenanzahl ein. Falls unbekannt bitte 0 angeben.."
            - Range:
                min: 0
                minMessage: "Negative Seitenzahlen sind sinnlos."
                max: 100000
                maxMessage: "Mehr als 100.000 Seiten sind unwahrscheinlich."

Vitoop\InfomgmtBundle\Entity\Flag:
    properties:
        info:
            - NotBlank:
                message: "Bitte gib' eine kurze Bemerkung bzw. Begründung ein. Danke!"
            - Length:
                max: 128
                maxMessage: "Deine Bemerkung darf nicht mehr als {{ limit }} Zeichen haben. Fasse Dich bitte kürzer, denn in der Kürze liegt die Würze."

Vitoop\InfomgmtBundle\Entity\ProjectData:
    properties:
        sheet:
            - NotBlank:
                message: "Das Projekt-Blatt darf nicht leer sein"
            - Length:
                max: 65536
                maxMessage: "Das Projekt-Blatt darf nicht mehr als 65536 Zeichen haben."

Vitoop\InfomgmtBundle\Entity\Tag:
    properties:
        text:
            - NotBlank:
                message: "Der Tag darf nicht leer sein"
            - Regex:
                pattern: "/^[\x20-\x7FäöüÄÖÜß]+$/"
                message: "Dein Tag enthält nicht erlaubte Sonderzeichen."

Vitoop\InfomgmtBundle\Entity\Comment:
    properties:
        text:
            - NotBlank:
                message: "Du solltest schon etwas schreiben."
            - Length:
                max: 512
                maxMessage: "Deine Bemerkung darf nicht mehr als {{ limit }} Zeichen haben."

Vitoop\InfomgmtBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: "Bitte gebe einen Usernamen an."
            - Length:
                min: 6
                minMessage: "Dein Username sollte mindestens {{ limit }} Zeichen haben."
                max: 16
                maxMessage: "Dein Username sollte nicht mehr als {{ limit }} Zeichen haben."
            - Regex:
                pattern: "/^[\x20-\x7FäöüÄÖÜß]+$/"
                message: "Dein Username enthält nicht erlaubte Zeichen."
            - Regex:
                pattern: "/(^gel-)/"
                match: false
                message: "Username cannot starts from 'gel-'"
        email:
            - Email:
                message: "Deine angegebene email {{ value }} is keine gültige email."
                checkMX: true
        password:
            - NotBlank:
                message: "Bitte gebe ein Passwort an."
            - Length:
                min: 8
                minMessage: "Dein Passwort sollte mindestens 8 Zeichen lang sein."
                max: 32
                maxMessage: "Dein Passwort ist zu lang({{ limit }} Zeichen). Bitte wähle ein kürzeres"
            - Regex:
                pattern: "/^[\x21-\x7FäöüÄÖÜß]+$/"
                message: "Dein Passwort enthält nicht erlaubte Zeichen."
            - Regex:
                pattern: "/^[0-9]+$/"
                match:   false
                message: "Dein Passwort enthält nur Zahlen."
            - Regex:
                pattern: "/^[a-zäöüß]+$/"
                match:   false
                message: "Dein Passwort enthält nur Kleinbuchstaben."
            - Regex:
                pattern: "/^[A-ZÄÖÜß]+$/"
                match:   false
                message: "Dein Passwort enthält nur Großbuchstaben."