<?php


namespace App\Repository;

use App\Entity\ConversationMessage;

/**
 * ConversationMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationMessageRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return ConversationMessage::class;
    }
}