<?php


namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\ConversationData;
use App\Entity\Resource;
use App\DTO\Resource\SearchResource;
use App\Entity\User\User;

/**
 * ConversationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationDataRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return ConversationData::class;
    }
}