<?php


namespace App\Repository;

use App\Entity\User\User;
use App\Entity\Conversation;
use App\DTO\Resource\SearchResource;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return Conversation::class;
    }

    public function getResourcesQuery(SearchResource $search)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r', 'conversationData.sheet')
            ->leftJoin('r.conversation_data', 'conversationData');

        $this->prepareListQueryBuilder($qb, $search);

        return $qb;
    }
}