<?php

namespace App\Repository;

use App\Entity\Conversation;
use App\Entity\RelConversationUser;
use App\Entity\User\User;


/**
 * RelConversationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelConversationUserRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return RelConversationUser::class;
    }

    public function addUser(RelConversationUser $user)
    {
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush();
    }

    public function removeUser(RelConversationUser $user)
    {
        $this->getEntityManager()->remove($user);
        $this->getEntityManager()->flush();
    }

    public function getRel(User $user, Conversation $conversation)
    {
        return $this->createQueryBuilder('rcu')
            ->select('rcu')
            ->where('rcu.user = :user')
            ->andWhere('rcu.conversationData = :conversationData')
            ->setParameter('conversationData', $conversation->getConversationData())
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}