<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\VitoopBlog;

/**
 * VitoopBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VitoopBlogRepository extends ServiceEntityRepository
{
    /**
     * VitoopBlogRepository constructor.
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, VitoopBlog::class);
    }

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findCurrent()
    {
        return $this->createQueryBuilder('vb')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function save(VitoopBlog $blog)
    {
        $this->getEntityManager()->persist($blog);
        $this->getEntityManager()->flush($blog);
    }
}