security:

   role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

   providers:
      user_db:
         entity: { class: VitoopInfomgmtBundle:User, property: username }
         
   encoders:
      Symfony\Component\Security\Core\User\User:  plaintext
      Vitoop\InfomgmtBundle\Entity\User:
         algorithm:   sha1
         iterations: 1
         encode_as_base64: false
   
   firewalls:
      dev:
         pattern:  ^/(_(profiler|wdt)|css|images|js)/
         security: false

      secured_infomgmt:
         pattern: ^/
         form_login:
            check_path: /login_check
            login_path: /login
            default_target_path: /userhome
            always_use_default_target_path: true
            failure_path: /login
            require_previous_session: false
            #target_path_parameter: the parameter in the hidden form field value="...
         logout:
            path:    /logout
            target:  /
         anonymous:  ~

   access_control:      
      - { path: ^/password/forgotPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/password/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: '^/register/[a-z0-9]{32}$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/invite, roles: ROLE_ADMIN }
      - { path: ^/edit-vitoop-blog, roles: ROLE_ADMIN }
      - { path: ^/, roles: ROLE_USER }
