services:
    vitoop.settings: '@Vitoop\InfomgmtBundle\Service\SettingsService'
    vitoop.downloads: '@Vitoop\InfomgmtBundle\Service\DownloadsService'
    vitoop.file_downloader: '@Vitoop\InfomgmtBundle\Service\FileDownloader'
    vitoop.resource_manager: '@Vitoop\InfomgmtBundle\Service\ResourceManager'
    vitoop.lexicon_query_manager: '@Vitoop\InfomgmtBundle\Service\LexiconQueryManager'
    vitoop.resource_data_collector: '@Vitoop\InfomgmtBundle\Service\ResourceDataCollector'
    vitoop.form_creator: '@Vitoop\InfomgmtBundle\Service\FormCreator'
    vitoop.vitoop_security: '@Vitoop\InfomgmtBundle\Service\VitoopSecurity'
    vitoop.user_config_manager: '@Vitoop\InfomgmtBundle\Service\UserConfigManager'
    vitoop.url_getter:  '@Vitoop\InfomgmtBundle\Service\UrlGetter'
    vitoop.url_checker: '@Vitoop\InfomgmtBundle\Service\UrlChecker'
    vitoop.email_sender: '@Vitoop\InfomgmtBundle\Service\EmailSender'

    buzz.client.curl: '@Buzz\Client\Curl'
    buzz.browser: '@Buzz\Browser'

    vitoop.repository.user: '@Vitoop\InfomgmtBundle\Repository\UserRepository'
    vitoop.repository.user_config: '@Vitoop\InfomgmtBundle\Repository\UserConfigRepository'
    vitoop.repository.invitation: '@Vitoop\InfomgmtBundle\Repository\InvitationRepository'
    vitoop.repository.resource: '@Vitoop\InfomgmtBundle\Repository\ResourceRepository'
    vitoop.repository.tag: '@Vitoop\InfomgmtBundle\Repository\TagRepository'
    vitoop.repository.rel_resource: '@Vitoop\InfomgmtBundle\Repository\RelResourceResourceRepository'
    vitoop.repository.rel_tag_resource: '@Vitoop\InfomgmtBundle\Repository\RelResourceTagRepository'
    vitoop.repository.lexicon: '@Vitoop\InfomgmtBundle\Repository\LexiconRepository'
    vitoop.repository.pdf_annotation: '@Vitoop\InfomgmtBundle\Repository\PdfAnnotationRepository'

    vitoop.validator.user_unique: '@Vitoop\InfomgmtBundle\Validator\Constraints\User\UserUniqueValidator'
    vitoop.validator.username: '@Vitoop\InfomgmtBundle\Validator\Constraints\User\UsernameValidator'
    vitoop.validator.user_email: '@Vitoop\InfomgmtBundle\Validator\Constraints\User\UserEmailValidator'
    vitoop.password_encoder.user: '@Vitoop\InfomgmtBundle\Service\User\UserPasswordEncoder'
    vitoop.generator.common_token: '@Vitoop\InfomgmtBundle\Utils\Token\CommonGeneratorStrategy'
    vitoop.tag.factory: '@Vitoop\InfomgmtBundle\Service\Tag\TagCreator'
    vitoop.resource_tag.linker: '@Vitoop\InfomgmtBundle\Service\Tag\ResourceTagLinker'
    vitoop.rel_resource.linker: '@Vitoop\InfomgmtBundle\Service\RelResource\RelResourceLinker'

    vitoop.form.type.res:
            class: Vitoop\InfomgmtBundle\Form\Type\ResourceType
            tags:
                - { name: form.type, alias: res }

    vitoop.form.type.pdf:
        class: Vitoop\InfomgmtBundle\Form\Type\PdfType
        tags:
            - { name: form.type, alias: pdf }

    vitoop.form.type.book:
        class: Vitoop\InfomgmtBundle\Form\Type\BookType
        tags:
            - { name: form.type, alias: book }

    vitoop.form.type.adr:
        class: Vitoop\InfomgmtBundle\Form\Type\AddressType
        tags:
            - { name: form.type, alias: adr }

    vitoop.form.type.link:
        class: Vitoop\InfomgmtBundle\Form\Type\LinkType
        tags:
            - { name: form.type, alias: link }

    vitoop.form.type.teli:
        class: Vitoop\InfomgmtBundle\Form\Type\TeliType
        tags:
            - { name: form.type, alias: teli }

    vitoop.form.type.lex:
        class: Vitoop\InfomgmtBundle\Form\Type\LexiconType
        tags:
            - { name: form.type, alias: lex }

    vitoop.form.type.prj:
        class: Vitoop\InfomgmtBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: prj }


    vitoop.form.type.rating:
        class: Vitoop\InfomgmtBundle\Form\Type\RatingType
        tags:
            - { name: form.type, alias: rating }

    vitoop.form.type.tag:
        class: Vitoop\InfomgmtBundle\Form\Type\TagType
        tags:
            - { name: form.type, alias: tag }

    vitoop.form.type.remark:
        class: Vitoop\InfomgmtBundle\Form\Type\RemarkType
        tags:
            - { name: form.type, alias: remark }

    vitoop.form.type.remark_private:
        class: Vitoop\InfomgmtBundle\Form\Type\RemarkPrivateType
        tags:
            - { name: form.type, alias: remark_private }

    vitoop.form.type.comment:
        class: Vitoop\InfomgmtBundle\Form\Type\CommentType
        tags:
            - { name: form.type, alias: comment }

    vitoop.form.type.lexicon.name:
        class: Vitoop\InfomgmtBundle\Form\Type\LexiconNameType
        tags:
            - { name: form.type, alias: lexicon_name }

    vitoop.form.type.project:
        class: Vitoop\InfomgmtBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: project }

    vitoop.form.type.project.name:
        class: Vitoop\InfomgmtBundle\Form\Type\ProjectNameType
        tags:
            - { name: form.type, alias: project_name }

    vitoop.form.type.flag:
        class: Vitoop\InfomgmtBundle\Form\Type\FlagType
        tags:
            - { name: form.type, alias: flag }

    vitoop.form.type.flaginfo:
        class: Vitoop\InfomgmtBundle\Form\Type\FlagInfoType
        tags:
            - { name: form.type, alias: flaginfo }

    vitoop.form.type.invitation:
        class: Vitoop\InfomgmtBundle\Form\Type\InvitationType
        tags:
            - { name: form.type, alias: invitation }

    vitoop.form.type.invitation_new:
        class: Vitoop\InfomgmtBundle\Form\Type\InvitationNewType
        tags:
            - { name: form.type, alias: invitation_new }

    vitoop.form.type.project_data:
        class: Vitoop\InfomgmtBundle\Form\Type\ProjectDataType
        tags:
            - { name: form.type, alias: project_data }

    vitoop.form.type.user_data:
        class: Vitoop\InfomgmtBundle\Form\Type\UserDataType
        tags:
            - { name: form.type, alias: user_data }

    vitoop.form.type.vitoop_blog:
        class: Vitoop\InfomgmtBundle\Form\Type\VitoopBlogType
        tags:
            - { name: form.type, alias: vitoop_blog }

    vitoop.form.type.input_type_submit:
        class: Vitoop\InfomgmtBundle\Form\Type\InputTypeSubmitType
        tags:
            - { name: form.type, alias: input_type_submit }


