security:

   role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

   providers:
      user_db:
         entity: { class: VitoopInfomgmtBundle:User, property: username }
         
   encoders:
      Symfony\Component\Security\Core\User\User:  plaintext
      Vitoop\InfomgmtBundle\Entity\User:
         algorithm:   sha1
         iterations: 1
         encode_as_base64: false
   
   firewalls:
      dev:
         pattern:  ^/(_(profiler|wdt)|css|images|js)/
         security: false

      secured_infomgmt:
         pattern: ^/
         logout_on_user_change: true
         form_login:
            check_path: /login_check
            login_path: /login
            default_target_path: /link/
            always_use_default_target_path: false
            failure_path: /login
            require_previous_session: false
            provider: user_db
            #target_path_parameter: the parameter in the hidden form field value="...
         guard:
            authenticators:
               - Vitoop\InfomgmtBundle\Service\Security\Guard\VitoopMainFormAuthenticator
         logout:
            path:    /logout
            target:  /login
         anonymous:  ~

   access_control:      
      - { path: ^/password/forgotPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/password/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/(login|userhome), roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/impressum, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/invitation/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/invitation/, roles: ROLE_ADMIN }  #deprecated
      - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: '^/register/[a-z0-9]{32}$', roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/invite, roles: ROLE_ADMIN } #deprecated
      - { path: ^/edit-vitoop-blog, roles: ROLE_ADMIN } #deprecated
      - { path: ^/api/help, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/(datap|agreement), roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/v1/users/passwords$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST, PUT]}
      - { path: ^/api/v1/vitoop-blog$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: GET}
      - { path: ^/api/v1/vitoop-blog, roles: ROLE_ADMIN, methods: PUT}
      - { path: ^/api/v1/invitations$, roles: ROLE_ADMIN, methods: POST}
      - { path: ^/api/v1/invitations, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: GET}
      - { path: ^/, roles: ROLE_USER }

