<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Vitoop\InfomgmtBundle\Entity\Project;
use Vitoop\InfomgmtBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends ResourceRepository
{
    public function getAllProjectsByTermOrAllIfLessThanTen($term, User $user)
    {
        // TODO ALL if less than ten
        $arr_result = $this->getEntityManager()
                           ->createQuery('SELECT p.name FROM VitoopInfomgmtBundle:Project p JOIN p.user u WHERE u=:arg_user AND p.name LIKE :arg_term  ORDER BY p.name ASC')
                           ->setParameters(array(
                'arg_user' => $user,
                'arg_term' => $term . "%"
            ))
                           ->getResult();

        if (!$arr_result) {
            return null;
        }
        $arr_flattened_result = array_map(function ($arr_element) {
            return $arr_element['name'];
        }, $arr_result);
        $json_result = '["' . implode('","', $arr_flattened_result) . '"]';

        return $json_result;
    }

    public function getProjectWithData($id)
    {
        // LEFT JOIN because JOIN would result null if there is no project_data
        return $this->getEntityManager()
                    ->createQuery('SELECT p, pd FROM VitoopInfomgmtBundle:Project p LEFT JOIN p.project_data pd WHERE p.id=:arg_id')
                    ->setParameters(array('arg_id' => $id))
                    ->getOneOrNullResult();
    }

    public function getCountOfRelatedResources(Project $project)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('count(prj.id) as prjc')
            ->addSelect('count(lex.id) as lexc')
            ->addSelect('count(pdf.id) as pdfc')
            ->addSelect('count(teli.id) as telic')
            ->addSelect('count(link.id) as linkc')
            ->addSelect('count(adr.id) as adrc')
            ->from('VitoopInfomgmtBundle:RelResourceResource', 'rrr')
            ->leftJoin('VitoopInfomgmtBundle:Project', 'prj', 'WITH', 'rrr.resource2 = prj.id')
            ->leftJoin('VitoopInfomgmtBundle:Lexicon', 'lex', 'WITH', 'rrr.resource2 = lex.id')
            ->leftJoin('VitoopInfomgmtBundle:Pdf', 'pdf', 'WITH', 'rrr.resource2 = pdf.id')
            ->leftJoin('VitoopInfomgmtBundle:Teli', 'teli', 'WITH', 'rrr.resource2 = teli.id')
            ->leftJoin('VitoopInfomgmtBundle:Link', 'link', 'WITH', 'rrr.resource2 = link.id')
            ->leftJoin('VitoopInfomgmtBundle:Address', 'adr', 'WITH', 'rrr.resource2 = adr.id')
            ->where('rrr.resource1 = :project')
            ->setParameter('project', $project)
            ->getQuery()
            ->getOneOrNullResult();
    }
}