<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Vitoop\InfomgmtBundle\Entity\RelResourceTag;
use Vitoop\InfomgmtBundle\Entity\Resource;
use Vitoop\InfomgmtBundle\Entity\Tag;
use Vitoop\InfomgmtBundle\Entity\User;

/**
 * RelResourceTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelResourceTagRepository extends EntityRepository
{
    public function exists(RelResourceTag $rrt)
    {

        return $this->getEntityManager()
                    ->createQuery('SELECT rrt.id FROM Vitoop\InfomgmtBundle\Entity\RelResourceTag rrt
            WHERE rrt.resource=:arg_resource AND rrt.tag=:arg_tag AND rrt.user=:arg_user')
                    ->setParameters(array(
                'arg_resource' => $rrt->getResource(),
                'arg_tag' => $rrt->getTag(),
                'arg_user' => $rrt->getUser()
            ))
                    ->getResult();
    }
}