<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Vitoop\InfomgmtBundle\DTO\Resource\SearchResource;
use Vitoop\InfomgmtBundle\Entity\Book;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return Book::class;
    }

    public function getResourcesQuery(SearchResource $search)
    {
        $qb = $this->createQueryBuilder('r')->select('r.author, r.tnop');
        $this->prepareListQueryBuilder($qb, $search);

        if ($search->art) {
            $qb
                ->andWhere('r.kind = :art')
                ->setParameter('art', $search->art);
        }


        return $qb;
    }
}