<?php


namespace Vitoop\InfomgmtBundle\Repository;

use Vitoop\InfomgmtBundle\Entity\User;
use Vitoop\InfomgmtBundle\Entity\Conversation;
use Vitoop\InfomgmtBundle\DTO\Resource\SearchResource;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends ResourceRepository
{
    public function getEntityClass()
    {
        return Conversation::class;
    }

    public function getResourcesQuery(SearchResource $search)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r', 'conversationData.sheet')
            ->leftJoin('r.conversation_data', 'conversationData');

        $this->prepareListQueryBuilder($qb, $search);

        return $qb;
    }

    public function getConversationById($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM ' . $this->getEntityName() . ' c WHERE c.id=:arg_id')
            ->setParameter('arg_id', $id)
            ->getResult();
    }
}