<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 0 = Not downloaded still
 * 1 = Downloaded on server
 * 4 = Download error (404 or something else)
 */
class PdfRepository extends ResourceRepository
{
    public function getPDFForDownloading($count, $missing)
    {
        $query = $this->createQueryBuilder('r')
            ->orderBy('r.created_at', 'ASC')
            ->setMaxResults($count);
        if (!$missing) {
            $query->where('r.isDownloaded = 0');
        } else {
            $query->where('r.isDownloaded != 1');
            $query->andWhere('r.isDownloaded != 0');
        }

        return $query->getQuery()->getResult();
    }

    public function getResources($flagged = false, $resource = null, $arr_tags = array(), $arr_tags_ignore = array(), $arr_tags_highlight = array(), $tag_cnt = 0)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select('r.author', 'r.url', 'r.tnop', 'r.isDownloaded');
        $this->prepareListQueryBuilder($qb, $flagged);
        if (!is_null($resource)) {
            $this->prepareListByResourceQueryBuilder($qb, $resource);
        } elseif (!empty($arr_tags)) {
            $this->prepareListByTagsQueryBuilder($qb, $arr_tags, $arr_tags_highlight, $arr_tags_ignore, $tag_cnt);
        }

        return $qb->getQuery()->getResult();
    }
}