<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Vitoop\InfomgmtBundle\Entity\Conversation;
use Vitoop\InfomgmtBundle\Entity\RelConversationUser;
use Vitoop\InfomgmtBundle\Entity\User;


/**
 * RelConversationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelConversationUserRepository extends EntityRepository
{
    public function getRel(User $user, Conversation $conversation)
    {
        return $this->createQueryBuilder('rcu')
            ->select('rcu')
            ->where('rcu.user = :user')
            ->andWhere('rcu.conversationData = :conversationData')
            ->setParameter('conversationData', $conversation->getConversationData())
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}