<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Vitoop\InfomgmtBundle\Entity\RelProjectUser;
use Vitoop\InfomgmtBundle\Entity\User;
use Vitoop\InfomgmtBundle\Entity\Project;

/**
 * RelProjectUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelProjectUserRepository extends EntityRepository
{
    public function getRel(User $user, Project $project)
    {
        return $this->createQueryBuilder('rpu')
            ->select('rpu')
            ->where('rpu.user = :user')
            ->andWhere('rpu.projectData = :projectData')
            ->setParameter('projectData', $project->getProjectData())
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}