<?php

namespace Vitoop\InfomgmtBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Vitoop\InfomgmtBundle\Entity\RelProjectUser;
use Vitoop\InfomgmtBundle\Entity\User;
use Vitoop\InfomgmtBundle\Entity\Project;

/**
 * RelProjectUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelProjectUserRepository extends ServiceEntityRepository
{
    /**
     * RelProjectUserRepository constructor.
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, RelProjectUser::class);
    }

    /**
     * @param RelProjectUser $user
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(RelProjectUser $user)
    {
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush($user);
    }

    public function getRel(User $user, Project $project)
    {
        return $this->createQueryBuilder('rpu')
            ->select('rpu')
            ->where('rpu.user = :user')
            ->andWhere('rpu.projectData = :projectData')
            ->setParameter('projectData', $project->getProjectData())
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}